extends:
  - cooperka/react
parser: babel-eslint
env:
  browser: true
  jest: true
globals:
  $: true
  I18n: true
  ELMO: true
rules:
  padded-blocks:
    - error
    - never
  react/prefer-stateless-function: off
