extends:
  - cooperka/react
parser: babel-eslint
env:
  browser: true
  jest: true
globals:
  $: true
  I18n: true
  ELMO: true
rules:
  import/no-unresolved: ['error', { ignore: ['^javascripts/'] }]
  react/prefer-stateless-function: off
