fail_on_violations: true
rubocop:
  enabled: true
  config_file: .rubocop.yml
  version: 0.83.0
eslint:
  enabled: false
  config_file: .eslintrc.yml
scss:
  enabled: true
  config_file: .scss-lint.yml
jshint:
  enabled: false
