# Disable defaults
AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  TargetRailsVersion: 4.2
  Exclude:
    - "bin/**/*"
    - "script/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "lib/**/*"

# Layout Rules
Layout:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Metrics Rules
Metrics:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 115

# Style rules
Style:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MixinGrouping:
  EnforcedStyle: grouped

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

# Miscellaneous rules

Bundler:
  Enabled: true

Rails:
  Enabled: true
