# NOTE: This now is the preferred place to put settings instead of configatron.

# The settings below are defaults for settings listed in config/settings.local.yml.example.
# They are included in case older systems don't have them defined.
# This way they can be relied upon in the codebase without nil checks.
# See config/settings.local.yml.example for documentation for these settings.
max_upload_size_mib: 50
paperclip:
  storage: local
